### PR TITLE
Featureready

### PR DESCRIPTION
**Pull request by ddddavis**
This project is built with

- Backgrounds and gradients
- Media queries to support all devices.
- Grids, flexbox positions, and floats.

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin (TSE)
Please check on this in a few minutes for the full review :handshake:

**Comment by nikasulo** [comment]
# Great work guys
Your project looks nice, however, you have missed one major breakpoint and as such your project isn't responding to the tablet screen size. Please pay attention to what happens from 1024px down to 768px. Also, look deeper into the mobile screen size(<768px) as a few of the sections need your attention. Please make these assessments and changes, comparing the original site to yours very closely, make the necessary changes and request another review.

I wish you the best in your next submission :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @davisdambis and @Tahirbhalli  :lollipop: :balloon: 

### I can see you made the changes requested by the previous TSE and your job so far is remarkable :clap: :medal_sports:  there are still some changes to work on :construction_worker_man: :building_construction: 

## Small screens

**Latest Fundings**

- [x] The order of the menu items at this screen size is:

1. See more
2. Get updates by email
3. Add info

- Yours

image

- Original

image

- [x] There should be 3 articles showing in this screen size your page is showing an extra one

- hide this article

image

**Footer**

- [x] The footer should have only 3 rows in the copy wright section, yours have 4

- Yours

image

- Original

image

## Big Screens (screen-width > 1024px) 

**Footer**

The copy wright section should be vertically centered, yours seems to be on the top of the section

- Yours

image

- Original

image

## Generals

**Apps, Gear, Tech, etc**

- [x] Please fix the tittles of your Apps, Gear, Tech, etc.. section, right now all the titles says Apps

**Latest Deals**

- [x] Please add the "See all deals" red link in the rightmost part of the section title

- Yours

image

- Original

image

**Footer**

- [x] The footer links have to be written in capital letters and have more separation in between, let's fix them!

- Yours

image

- Original

image

## Optional

- [ ] I really encourage the use of the `<main>` tag for the dominant content of the `<body>` of a document

### That's it, team! :raised_hands: it has been a blast to review this project :guitar: 

### Please :pray: do the changes :memo: and submit back for a code review when you are done :rocket: 

Happy Coding! :woman_technologist: 

Any questions? reach out to me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

**Comment by ddddavis** [comment]
- Changed sizing of top news to match actual webpage size
- Added proper order
- Removed last item from latest funding on the mobile version
- Fixed footer lines
- Added different names to categories
- Added see all deals on the left
- Changed color of the footer

**Review by mosesogwo — APPROVED** [review]
**Great job making the requested changes:+1:. You are good to :rocket:**

:trophy:You can now merge to master.

**Cheers:stars:**

**Pull request merged**
